### ISSUE TITLE
Cannot search by establishment

### ISSUE THREAD

**Issue by sotrustmtg** [emilianotisato/nova-google-autocomplete-field#6]
I am trying to search by business name and I cannot get this to pull results.  Typing out business names return no addresses (blank).
Any idea what I need to do?
I have tried the following:
` GoogleAutocomplete::make('Address')
                ->placeType('establishment')
                ->withValues(['latitude', 'longitude','formatted_address','name'])
                ->hideFromIndex()
                ->nullable(),`

**Comment by emilianotisato** [comment]
@sotrustmtg 

1) Do you see some error in the javascript console?
2) Did it work before without the placeType() specification, and now that you add it does not work? (I ask this to be sure you install it correctly and create your API keys, etc)

**Comment by sotrustmtg** [comment]
No error. I can type out an address and it auto returns that, just not type out a business name.



[https://esr-storage.s3.amazonaws.com/images/7525/76981/default/images/183875a78b57b0ace8.png?override=1517860310]

John Hamman

•

Manager of Digital Marketing


757-518-0700 ext. 55809

JHamman@SouthernTrust.com<mailto:JHamman@SouthernTrust.com>


4433 Corporation Lane | Suite 300 | Virginia Beach, VA 23462
www.SouthernTrust.com<https://www.southerntrust.com/>



[cid:image002.png@01D50587.DB057730]<https://www.facebook.com/SouthernTrustMortgage>

[cid:image003.png@01D50587.DB057730]<https://www.linkedin.com/company/southern-trust-mortgage/>

[cid:image004.png@01D50587.DB057730]<https://twitter.com/Southern_Trust>

[cid:image005.png@01D50587.DB057730]<https://www.instagram.com/southerntrust/>





[https://esr-storage.s3.amazonaws.com/images/7525/76981/images/5af314cab3cf1.png]<https://marketingrequest.southerntrust.com/>

Confidentiality Notice The information contained in this email is confidential and/or legally privileged. If you have received this email in error, please notify us immediately by reply email and then delete this message from your system. If you are not the intended recipient, you are hereby notified that any review, dissemination or copying of this email and its attachments, if any, or of the information contained herein, is strictly prohibited. Thank you

**Comment by nickpoulos** [comment]
Interesting, I am also seeing this behavior now.  No matter what I seem to pass in as 'placeType' I cannot get business results to return anymore.  But as far as I rememeber this feature was absolutely working very recently.  

I will be exploring this more in depth now, but I am going to check two things: 

One, if the additional PR allowing locationResults has broken something, at first glance it doesn't appear so, but we will see.  Other possibilities - I am wondering if this tidbit from the docs need to be investigated again:  "The exception is that you can safely mix the geocode and establishment types, but note that this will have the same effect as specifying no types."  

That is the reason I set the placeType to empty string for my purposes. I wonder if the underlying vue-google-autocomplete has changed somehow.

**Comment by nickpoulos** [comment]
Latest version is 0.7, so I just downgraded to 0.6, which doesn't have my placeType changes. I re-added the change(s) to add placeType, updated my resource with ->placeType(''), and I am now seeing Business names again.

**Comment by idragon81** [comment]
I did some debugging. Found that the nova-google-autocomplete field is setting the type but vue-google-autocomplete is not picking it up. I've fixed it in #8 and updated other references for consistency. Although it's a bit peculiar why this happened

**Comment by emilianotisato** [comment]
Fixed in #8
